### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Tontonitch**
Hello,
After fetching your dev and merging everything, I end with this pull request.
* indentations in the script now tab everywhere
* new option --report/-r, allowing short(todo) / long(normal, current+multiline for interface_health check) / html (current+html table for interface_health check). Generated HTML table is also compatible with icingaweb2 (icingaweb2 classes used so okay with icingaweb2 HTMLPurifier)
* new option --suboption/-s, allowing to specify what to check via the option. Default is to check everything. Done for interface_health check, where you can specify status, home-node, home-port. i.e.: -s "home-node,home-port" won't perform the check of the status.
* add icinga2 command definition of the plugin

Added also 
* fix default strCritical value not well set
* changed again indentations in the script now tab (rollbacked to simplify  …
previous merge), version history (should be completed), authors (should be completed) and help function

Hope that's ok now.
Can give you some screenshots of the generated table on icingaweb2, but the screenshot branch is not merged yet in your repo.

BR,
Yannick

### CODE REVIEW

**Comment by willemdh** [comment]
@Tontonitch Thanks a lot. Merging.. Can I ask on what NetApp Ontap version you are running the plugin?

**Comment by Tontonitch** [comment]
We run the plugin on Netapp Ontap 8.3.2P9.

For your info, hereunder the result of the generated HTML table. I'm waiting for some feedback from the system team, but it is definitely more usable than the normal output.
image

By the way, is it planned to create an official release soon? Indeed, lots of users (myself also) don't look at branches other than master. Me, in fact I missed some enhancements of your plugin done on branch dev, and I started to use other plugins for specific checks as the version on master branch didn't fit my needs.

**Comment by willemdh** [comment]
> I'm waiting for some feedback from the system team

Let me know when they think it's stable. 

I'll ask my NetApp colleague to test out the current dev branch. And if you both let me know it's ok, I'll make some time to pull it into master.

**Comment by Tontonitch** [comment]
Hello,
I've discussed with my colleagues and for them it is stable and much more readable than the default output.
Just one thing: the table is not printed when there's no warning/critical. Some people might want to see this table even if the plugin returns an ok state.

**Pull request merged**
